name: .NET Core  
on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
    - uses: actions/checkout@v2  
    - name: Setup .NET Core  
      uses: actions/setup-dotnet@v3 
      with:  
        global-json-file: global.json  
    - name: Install dependencies
      working-directory: ./src/AspNetCore.Json.SinglePolymorphicResponse
      run: dotnet restore  
    - name: Build
      working-directory: ./src/AspNetCore.Json.SinglePolymorphicResponse
      run: dotnet build --configuration Release --no-restore  
    - name: Test
      working-directory: ./src/AspNetCore.Json.SinglePolymorphicResponse
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/AspNetCore.Json.SinglePolymorphicResponse/AspNetCore.Json.SinglePolymorphicResponse.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
