name: .NET Core  
on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
    - uses: actions/checkout@v2  
    - name: Setup .NET Core  
      uses: actions/setup-dotnet@v3 
      with:  
        global-json-file: global.json  
    - name: Install dependencies
      working-directory: ./src/
      run: dotnet restore  
    - name: Build
      working-directory: ./src/
      run: dotnet build --configuration Release --no-restore  
    - name: Test
      working-directory: ./src/
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      working-directory: ./src/AspNetCore.Json.SinglePolymorphicResponse
      run: dotnet pack -o nupkgs
    - name: Publish
      working-directory: ./src/AspNetCore.Json.SinglePolymorphicResponse
      run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
